### ISSUE TITLE
Use actual creep body constants instead of their string equivalents

### ISSUE THREAD

**Issue by OrletSoir** [Jourloy/VIKING#9]
* [Here](https://github.com/Jourloy/VIKING/blob/125e314693a0272a789f1c3295eab9364c83fe4a/Console.js#L218-L235])
* [Here](https://github.com/Jourloy/VIKING/blob/125e314693a0272a789f1c3295eab9364c83fe4a/Console.js#L304-L321)
* [And here](https://github.com/Jourloy/VIKING/blob/125e314693a0272a789f1c3295eab9364c83fe4a/Console.js#L703-L736)

Use `TOUGH` instead of `"tough"`, and so forth. This will prevent accidental breakage in the future. Also that code would serve better if rewritten as a `switch` statement.

As a side note, it would be very nice to have attributions to the authors of code snippets used in the file. For example, [here is my code bits](https://github.com/Jourloy/VIKING/blob/125e314693a0272a789f1c3295eab9364c83fe4a/Console.js#L85-L183). You're more than welcome to include it, all I ask is a line somewhere, saying "hey, this code was given by Orlet on Screeps Slack" or some sort :)

**Comment by Jourloy** [comment]
Thank you. Yesterday I try find who did give me this code, but I didn't find :)
